### ISSUE TITLE
Single thread force evaluation on sharp IB using Q1Q1

### ISSUE THREAD

**Issue by Luckabarbeau** [lethe-cfd/lethe#472]
If the sharp IB solver is forced to use a single thread per MPI process when using Q1Q1 the force evaluation is wrong.
This can be recreated by adding the following line at the beginning of  the function GLSSharpNavierStokesSolver<dim>::solve() :
`MultithreadInfo::set_thread_limit(1); `
The best PRM to highlight this problem is the _static_stokes_ application test.

**Comment by blaisb** [comment]
@Luckabarbeau It seems that this bug is caused by the usage of a MappingQ with 1 and only 1.
If you force the mapping to be 2 or more (so if fe.velocity_order=1 you force it to 2, otherwise you don't do much) then you fix this bug completely. I'm not sure I understand why for the moment, but this is an easy fix.

If you replace line 218 by :
`  MappingQ<dim - 1, dim> local_face_map(
    (2 > this->simulation_parameters.fem_parameters.velocity_order) ?
      2 :
      this->simulation_parameters.fem_parameters.velocity_order,
    this->simulation_parameters.fem_parameters.qmapping_all);`

You will be good to go. I'll you make the PR on Monday :)

@mostanad this will fix your issue.

**Comment by mostanad** [comment]
Thanks, Bruno, Licka and the team for your nice help.
